---
title: "conditionals_loops"
author: "Jake Eisaguirre"
date: "8/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


```{r}
pm2_5 <- 48

if (pm2_5 < 100) {
  print("low to moderate risk")
} else if (pm2_5 <= 100 & pm2_5 < 150) {
  print("unhealthy for sensitive groups")
} else if (pm2_5 >= 150){
  print("health risk present")
}



```

```{r}
species <- "blue whale"

if (str_detect(species, pattern = "blue whale")) {
  print("you found a whale")
} else {
}


```

```{r}
max_airtemp_c <- 24.1
 
 if (max_airtemp_c > 27){
   print("temp too high")
 } else if (max_airtemp_c < 27) {
    print("temp is ok")
 }



```

```{r}
base_burrito <- 6.50
main_ingredient <- "chicken"

if (main_ingredient == "veggies"){
   print("base burrito = 6.50$")
} else if (main_ingredient == "chicken") {
   print("base burrito = 6.50$ + 2$")
} else if (main_ingredient == "steak") {
   print("base burrito = 6.50$ + 3.25$")
 }




```

```{r}
fish <- c(8, 10, 12, 23)


for (i in seq_along(fish)) {
  print(fish[i]/sum(fish))
}


```

```{r}

for (i in seq_along(month.name)) {
  print(paste(month.name[i], "is month", i))
}

```


